const translations = {
    en: {
        login: "Login",
        signup: "Sign Up",
        username: "Username",
        password: "Password",
        email: "Email",
        confirmPassword: "Confirm Password",
        dontHaveAccount: "Don't have an account? Sign up",
        alreadyHaveAccount: "Already have an account? Login",
        welcome: "Welcome to Our Platform",
        welcomeText: "Experience the future of digital interaction with our cutting-edge platform. Join us today and discover a world of possibilities.",
        getStarted: "Get Started",
        features: "Features",
        about: "About",
        contact: "Contact",
        logout: "Logout",
        modernDesign: "Modern Design",
        modernDesignText: "Beautiful and responsive design that works perfectly on all devices.",
        secureAuth: "Secure Authentication",
        secureAuthText: "State-of-the-art security measures to protect your data.",
        multiLang: "Multi-language Support",
        multiLangText: "Access our platform in multiple languages for a global experience."
    },
    es: {
        login: "Iniciar Sesión",
        signup: "Registrarse",
        username: "Nombre de Usuario",
        password: "Contraseña",
        email: "Correo Electrónico",
        confirmPassword: "Confirmar Contraseña",
        dontHaveAccount: "¿No tienes cuenta? Regístrate",
        alreadyHaveAccount: "¿Ya tienes cuenta? Inicia Sesión",
        welcome: "Bienvenido a Nuestra Plataforma",
        welcomeText: "Experimenta el futuro de la interacción digital con nuestra plataforma de vanguardia. Únete hoy y descubre un mundo de posibilidades.",
        getStarted: "Comenzar",
        features: "Características",
        about: "Acerca de",
        contact: "Contacto",
        logout: "Cerrar Sesión",
        modernDesign: "Diseño Moderno",
        modernDesignText: "Diseño hermoso y responsivo que funciona perfectamente en todos los dispositivos.",
        secureAuth: "Autenticación Segura",
        secureAuthText: "Medidas de seguridad de última generación para proteger tus datos.",
        multiLang: "Soporte Multiidioma",
        multiLangText: "Accede a nuestra plataforma en múltiples idiomas para una experiencia global."
    },
    fr: {
        login: "Connexion",
        signup: "S'inscrire",
        username: "Nom d'utilisateur",
        password: "Mot de passe",
        email: "Email",
        confirmPassword: "Confirmer le mot de passe",
        dontHaveAccount: "Vous n'avez pas de compte ? Inscrivez-vous",
        alreadyHaveAccount: "Vous avez déjà un compte ? Connectez-vous",
        welcome: "Bienvenue sur Notre Plateforme",
        welcomeText: "Découvrez l'avenir de l'interaction numérique avec notre plateforme de pointe. Rejoignez-nous aujourd'hui et découvrez un monde de possibilités.",
        getStarted: "Commencer",
        features: "Fonctionnalités",
        about: "À propos",
        contact: "Contact",
        logout: "Déconnexion",
        modernDesign: "Design Moderne",
        modernDesignText: "Design beau et réactif qui fonctionne parfaitement sur tous les appareils.",
        secureAuth: "Authentification Sécurisée",
        secureAuthText: "Mesures de sécurité de pointe pour protéger vos données.",
        multiLang: "Support Multilingue",
        multiLangText: "Accédez à notre plateforme dans plusieurs langues pour une expérience mondiale."
    },
    de: {
        login: "Anmelden",
        signup: "Registrieren",
        username: "Benutzername",
        password: "Passwort",
        email: "E-Mail",
        confirmPassword: "Passwort bestätigen",
        dontHaveAccount: "Noch kein Konto? Registrieren",
        alreadyHaveAccount: "Bereits ein Konto? Anmelden",
        welcome: "Willkommen auf unserer Plattform",
        welcomeText: "Erleben Sie die Zukunft der digitalen Interaktion mit unserer fortschrittlichen Plattform. Treten Sie heute bei und entdecken Sie eine Welt voller Möglichkeiten.",
        getStarted: "Loslegen",
        features: "Funktionen",
        about: "Über uns",
        contact: "Kontakt",
        logout: "Abmelden",
        modernDesign: "Modernes Design",
        modernDesignText: "Schönes und responsives Design, das auf allen Geräten perfekt funktioniert.",
        secureAuth: "Sichere Authentifizierung",
        secureAuthText: "Hochmoderne Sicherheitsmaßnahmen zum Schutz Ihrer Daten.",
        multiLang: "Mehrsprachige Unterstützung",
        multiLangText: "Greifen Sie auf unsere Plattform in mehreren Sprachen zu für eine globale Erfahrung."
    },
    he: {
        login: "התחברות",
        signup: "הרשמה",
        username: "שם משתמש",
        password: "סיסמה",
        email: "אימייל",
        confirmPassword: "אימות סיסמה",
        dontHaveAccount: "אין לך חשבון? הירשם",
        alreadyHaveAccount: "יש לך כבר חשבון? התחבר",
        welcome: "ברוכים הבאים לפלטפורמה שלנו",
        welcomeText: "חוו את עתיד האינטראקציה הדיגיטלית עם הפלטפורמה המתקדמת שלנו. הצטרפו היום וגלו עולם של אפשרויות.",
        getStarted: "התחל",
        features: "תכונות",
        about: "אודות",
        contact: "צור קשר",
        logout: "התנתק",
        modernDesign: "עיצוב מודרני",
        modernDesignText: "עיצוב יפה ותגובתי שעובד מושלם על כל המכשירים.",
        secureAuth: "אימות מאובטח",
        secureAuthText: "אמצעי אבטחה מתקדמים להגנה על הנתונים שלך.",
        multiLang: "תמיכה בשפות מרובות",
        multiLangText: "גש לפלטפורמה שלנו במספר שפות לחוויה גלובלית."
    }
}; 